### ISSUE TITLE
error processing request: _th_cat is not implemented for type CPUBoolType

### ISSUE THREAD

**Issue by saadehmd** [weigao95/mrcnn_ros#2]
Hi, i managed to successfully build mrcnn-benchmark and run their default inference test scripts and they work fine. i also ran mrcnn_ros/nodes/mrcnn_segment_server.py.
The server for maskrcnn_benchmark instance segmentation initialization OK!

 However i am not able to run mrcnn_ros/script/simple_mrcnn_client_test.py and getting the following error. Not sure if it is ROS related or if something wrong with mrcnn-benchmark build.

Traceback (most recent call last):
  File "simple_mrcnn_client_test.py", line 39, in <module>
    main()
  File "simple_mrcnn_client_test.py", line 33, in main
    response = instance_segment(request)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 515, in call
    responses = transport.receive_once()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 727, in receive_once
    p.read_messages(b, msg_queue, sock) 
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 353, in read_messages
    self._read_ok_byte(b, sock)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 336, in _read_ok_byte
    raise ServiceException("service [%s] responded with an error: %s"%(self.resolved_name, str))
rospy.service.ServiceException: service [/instance_segment] responded with an error: error processing request: _th_cat is not implemented for type CPUBoolType

**Comment by saadehmd** [comment]
I am trying to utilize the kPam package for a robotics pick and place application. I have tested the mankey_ros. It's working fine. Do i need mrcnn_ros for the manipulation task itself?
